"""Init migrate

Revision ID: bb154f4638b8
Revises: 
Create Date: 2025-06-01 19:33:34.083080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb154f4638b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repeat_types',
    sa.Column('repeat_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('repeat_type_id')
    )
    op.create_table('task_types',
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('task_type_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('plants',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('science_name', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('place', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('photos',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.Column('task_date', sa.Date(), nullable=True),
    sa.Column('repeat_type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.ForeignKeyConstraint(['repeat_type_id'], ['repeat_types.repeat_type_id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.task_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('calendar',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('main_photos',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.photo_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('note_name', sa.String(length=70), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.photo_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('main_photos')
    op.drop_table('calendar')
    op.drop_table('tasks')
    op.drop_table('photos')
    op.drop_table('plants')
    op.drop_table('users')
    op.drop_table('task_types')
    op.drop_table('repeat_types')
    # ### end Alembic commands ###
