"""add default value of user code and isActivated attribute

Revision ID: cc51ccc9cb7e
Revises: ea2a9400a97f
Create Date: 2025-06-06 10:54:20.297054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc51ccc9cb7e'
down_revision = 'ea2a9400a97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActivated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isActivated')

    # ### end Alembic commands ###
